### ISSUE TITLE
Incorrect instructions for building the cardano-node from source

### ISSUE THREAD

**Issue by perturbing** [cardano-foundation/developer-portal#1055]
Hi, 

The [page]( https://github.com/cardano-foundation/developer-portal/blob/staging/docs/get-started/installing-cardano-node.md) is incorrect, it still refers to an outdated version of libsodium (66f017f1). Node 1.35.7 uses rev dbb48cce5429cb6585c9034f002568964f1ce567 of libsodium and the new node 8.0.0 does as well.

and for reference for the new node consider [this](https://github.com/iquerejeta/cardano-node/blob/patch-1/doc/getting-started/install.md)

**Comment by rphair** [comment]
this was fixed by @os11k although in the same effort we might be tuning the instructions a bit (https://github.com/cardano-foundation/developer-portal/pull/1062#pullrequestreview-1425366951).
