### ISSUE TITLE
Add adabounties.io to showcase section

### ISSUE THREAD

**Issue by thenic95** [cardano-foundation/developer-portal#1107]
Just stumbled upon https://adabounties.io/ and I'm not sure what categories I should use in the showcase section. In my opinion non of the existing ones really match . What do you think?

**Comment by rphair** [comment]
we'll have a `funding` category as soon as this old PR is merged: https://github.com/cardano-foundation/developer-portal/pull/1043#issuecomment-1627400165

**Comment by thenic95** [comment]
Thank you @rphair , I will use this tag once it's available.
