### ISSUE TITLE
Tag Lace wallet as open-source

### ISSUE THREAD

**Issue by DominicZ8** [cardano-foundation/developer-portal#1117]
Lace.io wallet went fully open-source in June 2023, according to their blog post: [https://www.lace.io/blog/unleashing-the-power-of-web3-lace-goes-open-source](https://www.lace.io/blog/unleashing-the-power-of-web3-lace-goes-open-source)

This should be updated in the wallet overview:
https://developers.cardano.org/showcase/?tags=wallet

**Comment by rphair** [comment]
Thanks @DominicZ8 for noticing & reporting 🤓 ... fixed by https://github.com/cardano-foundation/developer-portal/pull/1118
