### ISSUE TITLE
CIP relative links: build script fails when not anchored in current directory

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/developer-portal#1121]
Happening now that https://github.com/cardano-foundation/CIPs/pull/242 is merged (yesterday) into their `master` branch and will affect all builds from our `staging` branch until a fix is merged.  Most notably affecting https://github.com/cardano-foundation/developer-portal/pull/1005 and will affect anything else built via the CI more recently.  I'll submit a fix for this upstream and report back here.

**Comment by katomm** [comment]
Thank you @rphair for bringing this also to the developer portal. As written in the other issue, the portal must not rely on it, and the script must not be so fragile.

**Comment by katomm** [comment]
@rphair  I have yet to test through all the possible cases, but from what I can see, #1122 should fix or significantly improve the problem.

**Comment by rphair** [comment]
OK, since this has been reopened for the more general case I'm retitling it accordingly 🤓

**Comment by rphair** [comment]
@katomm @fill cross-referencing #1229.

**Comment by rphair** [comment]
This has been getting some visibility with the newer #1262 and I've been watching for CIP related build failures for a while, I believe this issue indeed has been fixed by #1122.  cc @fill-the-fill @katomm
