### ISSUE TITLE
Installing cardano-node for sanchonet requires BLST and cabal 3.8.1.0

### ISSUE THREAD

**Issue by thenic95** [cardano-foundation/developer-portal#1161]
Hi,
when trying to build a node for sanchonet one crucial step is missing in the install [node tutorial](https://developers.cardano.org/docs/get-started/installing-cardano-node/) and that is to [install BLST](https://github.com/input-output-hk/cardano-node-wiki/blob/main/docs/getting-started/install.md#installing-blst) should we add this to the existing tutorial?

The latest releases also require a newer version of cabal (3.8.1.0) instead of the version mentioned in the tutorial at the moment which is 3.6.2.0.

**Comment by rdlrt** [comment]
We certainly should, but I imagine that would go hand in hand with updating node release to "beyond" 8.1.2 (which atm is not yet a recommended on mainnet and not released). But certainly could be a draft PR that we could keep ready in anticipation

**Comment by katomm** [comment]
I believe it is save to close this after being addressed in #1287. If not please let me know.
