### ISSUE TITLE
CIP assets: images missing if in folder itself or for CPSs

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/developer-portal#1210]
The current title states my best guess at the reason for the reason `staging` currently does not build: due to the recent merge of CPS-0010 (https://github.com/cardano-foundation/CIPs/pull/619) and judging by the CIP build script output because of the image pathnames in that GitHub source (https://github.com/cardano-foundation/CIPs/blob/master/CPS-0010/README.md):
```
Error: Image docs/governance/cardano-problem-statements/no-data-wallet.drawio.png used in docs/governance/cardano-problem-statements/CPS-0010.md not found.
    at async Promise.all (index 0)
[ERROR] Client bundle compiled with errors therefore further build is impossible.
```
The CPS-0010 source uses the same relative-pathname syntax as successfully used for the images in CIP-0050... so my guess (not looking at the scripts yet; needed to prioritise reporting this problem while still on a bad Internet connection) is that either:
- the prepended `/images` folder for CIP-0050 allows the script to recognise that there are assets to collect... but doesn't work for images in the CIP folder itself; or:
- whatever rule is used to collect those images is only being run for `CIP-` documents but not for `CPS-` documents.

This is a hasty report, with some guesswork, since I'm still travelling almost daily & just wanted to blow the whistle on this, since it's affecting the CI build checking for all PRs open on the Dev Portal.  cc @katomm @fill-the-fill @ryun1

**Comment by fill-the-fill** [comment]
Sorry, didn't see this before, I will take it on me
