### ISSUE TITLE
OK to add new elements to new CPS data structure & outline?

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/developer-portal#1221]
@fill-the-fill (cc @katomm) the CIP Editors urgently (because of concurrent CPS drafts) need to merge https://github.com/cardano-foundation/CIPs/pull/764 which makes the following changes to all CPS documents:
- adds `License:` to the YAML front matter
- ~adds a `## Copyright` section header & content, generally at the end~ (**edit:** not worried about this)

Can you confirm that this will not break the CIP/CPS part of the site builders... either the Dev Portal or `cips.cardano.org`... when we merge https://github.com/cardano-foundation/CIPs/pull/764 and these documents get updated?

My understanding of these scripts is that extra (but properly formatted) fields in the YAML will be ignored and the unconventional sections will be simply passed through, but we would especially like to be sure about the YAML header.

Also it would be a good time I think to call attention to the old PR https://github.com/cardano-foundation/developer-portal/pull/1135 which is not about fixing/breaking anything but rather giving a better presentation to the data that has already been there.  It could be so for the `License:` data (though generally CPSs will be CC licensed, so sorting or filtering on this field will not be very interesting).

cc @Ryun1 @Crypto2099 @KtorZ

**Comment by rphair** [comment]
p.s. @fill-the-fill we have @katomm's earlier assurance that the added Copyright section won't be a problem (https://github.com/cardano-foundation/CIPs/issues/731#issuecomment-1880030796) so this question is just whether `License:` being added to the YAML will break anything.

**Comment by katomm** [comment]
If adding a yaml element can break anything I am worried.

**Comment by rphair** [comment]
@katomm we haven't run into that issue every often since the CIP format hasn't changed very often.  Maybe you could remember back to the period a couple years ago when CIP-0001 itself was updated and soon CIPs had a bunch of new YAML fields and a number of old ones were gradually retired.

In the period that followed there were CIPs in both formats, following 2 different YAML conventions (we only recently resolved this in https://github.com/cardano-foundation/CIPs/issues/389).

So a helpful question would be: did the YAML scripts have to be updated _in advance_ of the CIPs being merged that followed the new format... or were the scripts simply adjusted at leisure later to digest the new information properly?

**Comment by rphair** [comment]
@katomm @fill-the-fill I've testing a local build immediately after merging the CPS YAML & template changes of https://github.com/cardano-foundation/CIPs/pull/764 and `staging` builds without errors and works fine for the CPS pages, including the final _CPS Information_ extracted from the YAML.  Plus, for the first time all official CPSs now have proper Copyright information 😇 (cc @Ryun1 @Crypto2099)

@fill-the-fill (cc @KtorZ) it would likewise be worth checking the staging build of `cips.cardano.org` but I'm less sure how to do that. 🤔
