### ISSUE TITLE
include testnet-alonzo-genesis.json in "running cardano-node"

### ISSUE THREAD

**Issue by tweakch** [cardano-foundation/developer-portal#125]
I was testing the [running cardano-node](https://developers.cardano.org/docs/get-started/running-cardano#configuration-files) section using the prebuilt binaries [build 6907168](https://hydra.iohk.io/build/6907168) and noticed the `testnet-alonzo-genesis.json` is missing from the list of configuration files [here](https://developers.cardano.org/docs/get-started/running-cardano#mainnet--production)

I will finish the tutorial on the website, fix the issues I see and submit a PR later

**Comment by Mercurial** [comment]
Hi, the developer portal is intentionally not including any Testnet content as of right now. The goal of the developer portal is to showcase what you can do currently in the Mainnet.
