### ISSUE TITLE
Broken links silently redirect to unrelated pages

### ISSUE THREAD

**Issue by klntsky** [cardano-foundation/developer-portal#1258]
We maintain some docs for our tooling that reference the developer portal.
We have a CI check that ensures our links do not point to 404 pages.
The problem is that some pages were deleted on the portal, but the redirects do not let the user see their equivalents.

E.g. https://developers.cardano.org/docs/stake-pool-course/handbook/keys-addresses/ which used to point to a guide on key generation redirects to https://developers.cardano.org/docs/operate-a-stake-pool/ now.

Ideally the redirects should point to the same articles if they are moved, or respond with a 404 so that we can see that some of our links are outdated.

**Comment by rphair** [comment]
@klntsky this is fixed by https://github.com/cardano-foundation/developer-portal/pull/1280 unless you have inventoried any broken links or improper redirects beyond the SPO course (please post here whether or not).  cc @katomm
