### ISSUE TITLE
 Can't process doc metadata for doc at path developer-portal/docs/governance/cardano-improvement-proposals/CIP-0112.md

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#1269]
Looks like the current staging branch is suffering from an issue where the build gets broken by a CIP-0112.md file. Full error message:

`[ERROR] Error while parsing Markdown front matter.
This can happen if you use special characters in front matter values (try using double quotes around that value).
[ERROR] Loading of version failed for version current
[ERROR] Unable to build website for locale en.
[ERROR] Error: Can't process doc metadata for doc at path path=/Users/tommy/Sites/developer-portal/docs/governance/cardano-improvement-proposals/CIP-0112.md in version name=current
    at processDocMetadata (/Users/tommy/Sites/developer-portal/node_modules/@docusaurus/plugin-content-docs/lib/docs.js:200:15)
    at async Promise.all (index 173)
`

I wasn't able to look into this in detail but if this blocks you at the moment, you can just delete the file developer-portal/docs/governance/cardano-improvement-proposals/CIP-0112.md and go ahead. Please be aware that any "yarn build" command will pull again the broken file. 

Interestingly there is no CIP-0112.md in https://github.com/cardano-foundation/CIPs 

tagging for visibility: @rphair @Ryun1

**Comment by Ryun1** [comment]
Probably the incorrect naming on this folder [CIPs/cip-observe-script-context](https://github.com/cardano-foundation/CIPs/tree/master/cip-observe-script-type) 
whoops ! 😆

we will get i fixed

**Comment by rphair** [comment]
thanks @katomm for noticing... cc @Ryun1 - Fixed by https://github.com/cardano-foundation/CIPs/pull/830

**Comment by rphair** [comment]
Tested build is successful again via https://github.com/cardano-foundation/developer-portal/actions/runs/9240204785/job/25540538524 for currently open PR https://github.com/cardano-foundation/developer-portal/pull/1262 (cc @katomm)

**Comment by katomm** [comment]
Great work, thanks.
