### ISSUE TITLE
remove obsolete `--mary-era` option in faucet article

### ISSUE THREAD

**Issue by tweakch** [cardano-foundation/developer-portal#134]
Following the guide at [Explore Cardano Wallet](https://developers.cardano.org/docs/integrate-cardano/creating-wallet-faucet/#creating-a-wallet) I get the following error when querying wallets for UTxOs

```sh
cardano-cli query utxo --mary-era --testnet-magic 1097911063 --address $(cat ~/cardano/keys/payment1.addr)
```

```sh
Invalid option `--mary-era'
Usage: cardano-cli query utxo [--shelley-mode | --byron-mode 
                                [--epoch-slots NATURAL] |
                                --cardano-mode [--epoch-slots NATURAL]] 
                              (--whole-utxo | (--address ADDRESS) | 
                                (--tx-in TX-IN)) 
                              (--mainnet | --testnet-magic NATURAL) 
                              [--out-file FILE]
  Get a portion of the current UTxO: by tx in, by address or the whole.
```

Works fine without the `--mary-era` option.

**Comment by tweakch** [comment]
These era options are confusing me a bit... I had some issues with them when querying an unsynced chain before but that was regarding `shelley` or `byron-mode` if I recall correctly...  can someone explain what the `--mary-era` option used to do?

**Comment by ilyaLibin** [comment]
It should be OK to use without any flag.

**Comment by Bruheart** [comment]
Hi, Newbie here.

Could you let me know what you mean by flag?
"It should be OK to use without any flag."

Thanks,

**Comment by Bruheart** [comment]
Nevermind re: flag __ It's a line in terminal : }

Yes it does work without  --mary-era flag
