### ISSUE TITLE
author images broken 

### ISSUE THREAD

**Issue by gufmar** [cardano-foundation/developer-portal#1350]
The author images are no longer displayed as expected

https://developers.cardano.org/blog/

**Comment by rphair** [comment]
cc @katomm re: CSP problem suspected

**Comment by katomm** [comment]
Thanks, I'm aware. I'd suggest to go the route we took on https://cardano.org/news. 

With the author file and self hosted images. Way better to maintain.

**Comment by katomm** [comment]
Please see #1361
