### ISSUE TITLE
Proposal to replace "changelog" with "releases"

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#1361]
Hello all,
I believe we did quite a mistake when we decided to go with https://developers.cardano.org/changelog instead of the normal GitHub releases (for example on cardano.org: https://github.com/cardano-foundation/cardano-org/releases) While the changelog looks nice, it relies on plugins and maintenance that are becoming increasingly challenging to manage.

I suggest retroactively tagging all past releases, documenting them and creating the releases. (then consistently tagging releases moving forward)

I’m happy to handle this, though there’s one limitation: GitHub release dates are always set to the current date (“now”), so the historical releases would show incorrect dates.

Despite this drawback, I believe it’s still worth doing for better version tracking, organization and upgrades in the future. Please let me know what you think.

**Comment by rdlrt** [comment]
Cant we maintain a seperate markdown page in the repo for historical releases, and link to it in our first github release?
We can still add tag in github for previous commits against changelogs - and use those as hyperlinks, so it should be OK to map.

It is a one-time effort but feels cleaner than have adding x amount of releases now..

**Comment by katomm** [comment]
Yes of course.

**Comment by katomm** [comment]
Update: when I wrote "yes of course" I obv forgot that this is a plugin. And I remember now that I knew that. I was hoping for some reason that a script would create a static page. We cannot simply link to it without maintaining it, it will haunt us.

**Comment by rdlrt** [comment]
It is not something we should be maintaining post initial release. It would act as a historical changelog (reusing current changelog) prior to when releases were introduced.

**Comment by katomm** [comment]
I'm preparing a solution as we speak.

**Comment by katomm** [comment]
All releases between February 28, 2021 and June 30, 2024: https://developers.cardano.org/docs/portal-old-changelog/
