### ISSUE TITLE
Proposal to remove CIPs from the developer portal

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#1362]
Hello,

I want to revisit what I wrote in #1335 and expand on it. When we launched https://developers.cardano.org, https://cips.cardano.org was not in an optimal state. Browsing or searching for CIPs was challenging, so we made a considerable effort to integrate CIPs into the developer portal from the start.

Currently, the developer portal is (somewhat) stuck on the 2.xx version of Docusaurus because of this integration. The list of compromises to maintain this setup continues to grow, and I believe we’ve reached a point where it’s worth questioning whether to remove CIPs from the portal altogether.

That said, https://cips.cardano.org has significantly improved over the past few years. One alternative could be indexing cips.cardano.org with the Developer Portal’s search functionality. This way, users could search for CIP content through the Developer Portal and be redirected directly to cips.cardano.org. While this would require substantial initial work, it would greatly reduce maintenance efforts in the long run. (However, this is outside the scope of this proposal.)

Some relevant references (but the list of issues is huge):
#1157
#1335
#1135
#1122
#1106

**Comment by rdlrt** [comment]
Have always felt avoiding duplication for documntation of same content is best, especially with the said improvements at source site. This would be a welcome change

**Comment by ariady-putra** [comment]
| This is Navigable | This is Not |
|-------------------|-------------|
| ![image](https://github.com/user-attachments/assets/30e56aca-4cae-4f3d-a481-3bb6c4457db4) | ![image](https://github.com/user-attachments/assets/d2fb5188-e386-4595-acf4-d3aca7d4ed9e) |

No sidebar for easy overview. Wasted screenspace.

Sad,
![image](https://github.com/user-attachments/assets/12f54c67-8ec9-42a8-bf3f-2881ab189cbb)

**Comment by katomm** [comment]
@ariady-putra needs to be flagged on their side.

**Comment by rphair** [comment]
@katomm @ariady-putra I've submitted this issue here to hopefully get discussion going ASAP:
- https://github.com/cardano-foundation/cf-cip-frontend/issues/39
