### ISSUE TITLE
Incorrect link on Catalyst page

### ISSUE THREAD

**Issue by ADAmint2019** [cardano-foundation/developer-portal#170]
On this page:
https://developers.cardano.org/docs/fund-your-project/project-catalyst
Bottom section : FAQ
Top Link: Participation FAQ
This link leads to a generic page about Ideascale, which also shows how to VOTE inside Ideascale. This will lead folks astray.

I do not see any need to utilize this link, since we have two other FAQ listed there in that section which cover the need.

**Comment by katomm** [comment]
Thanks for flagging, makes sense. Do you want to create a pull request for this?

**Comment by ADAmint2019** [comment]
I have never done that, and have never used Github as a developer. 

All my best,

Steven Aldrich
(904) 479-5661
***@***.*** ***@***.***>
First Coast Computer Services


www.fccspro.com <https://www.fccspro.com/>
First Coast Computer Services is a Service Mark of First Coast Business Consultants, LLC.

**Comment by katomm** [comment]
No worries, Steven! (I just recognized you now) I will take care of it and I'm happy to have a Catalyst expert here :)

**Comment by ADAmint2019** [comment]
Awesome…  Thanks Tommy!
Yeah, my Github user is an old throwback to the ITN days…  Sorry I should have included my name in the body.

All my best,

Steven Aldrich
(904) 479-5661
***@***.*** ***@***.***>
First Coast Computer Services


www.fccspro.com <https://www.fccspro.com/>
First Coast Computer Services is a Service Mark of First Coast Business Consultants, LLC.

**Comment by katomm** [comment]
Fixed in #178
