### ISSUE TITLE
Broken link / missing Grafana guide in lesson-5.md

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#177]
docs/stake-pool-course/lesson-5.md links to https://docs.cardano.org/projects/cardano-node/en/latest/logging-monitoring/grafana.html but it seems this was removed. 

My suggestion is to add a new Grafana guide directly in the portal.

**Comment by pastuh** [comment]
Looks like exist more broken links.. 
Example:
https://developers.cardano.org/docs/stake-pool-course/lesson-1/

Redirects to: https://developers.cardano.org/docs/stake-pool-course/lesson-1/handbook/setup-virtual-box-written
Correct link: https://developers.cardano.org/docs/stake-pool-course/handbook/setup-virtual-box-written/
