### ISSUE TITLE
More advanced payment integration

### ISSUE THREAD

**Issue by Pic2490** [cardano-foundation/developer-portal#303]
I understand this is all new and still very early but I'm wondering if more advanced payment integration is possible. I went through the example of accepting payments, but I have an app releasing soon where I charge the customer through credit card only after my service takes place.

1)  I'm able to place a hold on their credit card for x amount and then their order is sent to my server if there's enough funds.
2) After service is done, I replace the hold on their credit card with variables on what happened during the service(ex: An Uber driver driving 8 miles is going to charge the customer less than driving 20 miles).

Am I able to replicate this kind of flow with Cardano? I'm a holder and was hoping this flow was possible with the blockchain. Again, I understand this is still early but I would love to have Cardano integrated with my app if possible. Thanks.

**Comment by Pic2490** [comment]
Also it might be possible to change this flow around if there was some way to check the customer's ADA balance?

**Comment by rdlrt** [comment]
> Is it possible?

Yes - but it almost is a call out for a support group to walk through the components and working instead of a step-by-step guide

**Comment by Pic2490** [comment]
> > Is it possible?
> 
> Yes - but it almost is a call out for a support group to walk through the components and workings distributed across pages instead of a step-by-step guide on a single page for specific use case

I've been looking at pages the past 2 days, can you point me towards the right resources? The reason why I ask is because I'm bound by the rules that:

1) Crypto transactions cannot be changed once sent(See #2, my app changing the credit card hold after service is complete )

2)  If I refund their ADA because they aren't able to find a service provider, they'll incur fees from transferring so it isn't an option for them to send ADA first and then have the rest of the app run. My service has to complete before they make a transaction

Is this where smart contracts come in/is the only option? Thanks

**Comment by Pic2490** [comment]
I'll repost somwhere else. But please provide more advance payment examples in the future. https://developers.cardano.org/docs/integrate-cardano/listening-for-payments-cli/

**Comment by tweakch** [comment]
There are multiple ways to achieve your usecase. One would be through smart contracts. Rhyst from STOIC Pool has a nice set of videos about your usecase. (Locking Funds for X amount of time, charging penalties, cancellation fees). This might give you an idea on whats possible

[Part 1](https://youtu.be/UQK-o3BPy28)
[Part 2](https://youtu.be/MLpJ4D8_n6I)
