### ISSUE TITLE
Bring the guides to node version 1.30.x (or latest)

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#308]
We really need to bring all the guides to node version 1.30.x (or latest). (#293)

**Comment by os11k** [comment]
Hi! I just wanted to start work on this, but I was thinking about 1.30.1. Any particular reason to go with 1.29?

**Comment by os11k** [comment]
Just to confirm, this page needs to be updated:
https://developers.cardano.org/docs/get-started/installing-cardano-node/
Right?

**Comment by tweakch** [comment]
hi @os11k 

> Hi! I just wanted to start work on this, but I was thinking about 1.30.1. Any particular reason to go with 1.29?

I think there isn't. we can use 1.30 since it is the latest release. right @katomm?

> Just to confirm, this page needs to be updated: https://developers.cardano.org/docs/get-started/installing-cardano-node/ Right?

yes, ghc is at 0.1.17. if I remember correctly, so the listings are outdated. might make sense to use a similar approach as in #300 to keep the listings up to date

**Comment by rdlrt** [comment]
> Just to confirm, this page needs to be updated: https://developers.cardano.org/docs/get-started/installing-cardano-node/ Right?

No, that page already refers to latest tag without hardcoded version references.

There are other sections that need to be bought in sync (Wallets, Operate a Pool, any CLI command arrears in minting guides)

**Comment by katomm** [comment]
> I think there isn't. we can use 1.30 since it is the latest release. right @katomm?

Yes, 1.30.x (or latest) makes sense.
