### ISSUE TITLE
Burning tokens via cardano-wallet-js?

### ISSUE THREAD

**Issue by theHour** [cardano-foundation/developer-portal#357]
Hey I've been reading about cardano-wallet-js.
I can see they provide an example on how to mint and send minted native tokens (this works without any issues), however I am interested is it possible to burn native tokens via this library?

**Comment by rdlrt** [comment]
The project repository for cardano-wallet-js is [here](https://github.com/tango-crypto/cardano-wallet-js), you might want to raise it there
