### ISSUE TITLE
Stripping Videos from Stakepool Course

### ISSUE THREAD

**Issue by rdlrt** [cardano-foundation/developer-portal#41]
Just a backlog issue, to see if it is beneficial to have SPO Videos in SPO school (as against commands), due to the nature and the videos being quickly out-of-date with current releases - as well as inability to maintain it outside of controller of the videos.

**Comment by tweakch** [comment]
About replacing content... Publishing the videos on Vimeo could help (a bit) because there you can "replace" or update a video without changing the link. If you re-upload a YouTube video the link changes. However, this does not address the maintainability issue @rdlrt talks about.

**Comment by katomm** [comment]
Thanks for the hint. Of course, it not only has advantages if someone can simply replace the video that we are embedding.

**Comment by sanskys** [comment]
since Stake Pool revamp is done, this issue can be closed?

**Comment by rdlrt** [comment]
Yip
