### ISSUE TITLE
Take a look at the Plutus Tutorial link is not working. 

### ISSUE THREAD

**Issue by zootechdrum** [cardano-foundation/developer-portal#426]
https://developers.cardano.org/docs/smart-contracts/plutus

The link found on this paragraph does not work 

Take a look at the Plutus Tutorial if you want to learn Plutus from the beginning. If you don't know Haskell yet, consider starting with Haskell.

**Comment by mcamendoza1** [comment]
@zootechdrum from discord. 
https://plutus-pioneer-program.readthedocs.io/en/latest/index.html

**Comment by sunapi386** [comment]
These notes describe how to locally host a Plutus Playground webpage, I don't see there are any ready instances hosted online to try out.
