### ISSUE TITLE
Broken link at "how to compile and test a Plutus App"

### ISSUE THREAD

**Issue by discosultan** [cardano-foundation/developer-portal#463]
In https://github.com/cardano-foundation/developer-portal/blob/d1255d82f19c775c610f6a0bd2291856ac45be85/docs/smart-contracts/plutus.md (taken from latest staging branch), the link at [how to compile and test a Plutus App](https://plutus.readthedocs.io/en/latest/plutus/tutorials/plutus-playground.html) is broken.

**Comment by katomm** [comment]
Thanks for flagging @discosultan. It doesn't seem to be on the site at all anymore and needs to be removed. Can you confirm this?
