### ISSUE TITLE
Unable to get transaction hash and index of the UTXO to spend

### ISSUE THREAD

**Issue by pradeeppks** [cardano-foundation/developer-portal#544]
Hi,

We have configured Cardano node with mainnet and node is running but we are unable to get transaction hash and index of the UTXO to spend. Please help us  to resolve and we are looking any suggestion.

Thanks.
![cardano](https://user-images.githubusercontent.com/23722702/156997322-95060b94-f961-46f3-8f1e-18fe5bdbf35a.PNG)

**Comment by Mercurial** [comment]
this could mean that the wallet doesn't have any balance available to spend or you are looking at the wrong wallet

**Comment by rdlrt** [comment]
1. Use testnet for experimenting
2. You can only use a UTxO as input (which can still be a draft tx and executed after the draft).
3. Developer Portal is not the best place for support queries, you might want to use https://forum.cardano.org or https://cardano.stackexchange.com/
