### ISSUE TITLE
Grafana Loki for SPOs page in Handbook

### ISSUE THREAD

**Issue by os11k** [cardano-foundation/developer-portal#616]
Hi!

I recently created documentation how to use Loki as centralized logging solution for SPOs:

https://forum.cardano.org/t/grafana-loki-as-centralized-log-solutions-for-pool-operators/100824

I propose to create page with same information under Handbook, I think it will be quite nice addition.

What you think?

**Comment by rphair** [comment]
Just found the posting at https://forum.cardano.org/t/grafana-loki-as-centralized-log-solutions-for-pool-operators/100824 and I think it would make a _great_ addition 🤩

**Comment by os11k** [comment]
Hi! Thank you for a feedback, will add this manual to developer portal on some weekends.

**Comment by katomm** [comment]
I second this, great addition. Worth to mention there is an effort to revamp the stake pool category on #737, likely makes sense to do the PR against [revamp-stake-pool-course](https://github.com/cardano-foundation/developer-portal/tree/revamp-stake-pool-course) branch
