### ISSUE TITLE
Missing ADA's in transfer !

### ISSUE THREAD

**Issue by 7mezi** [cardano-foundation/developer-portal#637]
Hi all,

I have transferred 500+ ADA from my Nami wallet to my Binance account, it has been 7 hours already and the funds haven't shown up, even though the transaction went through normally and the ADA's left the wallet immediately.

Please help!

**Comment by rdlrt** [comment]
This repository is for updates to [developer portal](https://developers.cardano.org) website. You can check the list of community channels at [this forum post](https://forum.cardano.org/t/cardano-stay-safe-series-official-community-channel-list/20046) for any assistance.
For mentioned case, you'd want to check if your balance is deducted from your source using an explorer , and then follow-up with the binance or nami support depending on where you see descrepancy
