### ISSUE TITLE
Please add NFT vending machine python scripts

### ISSUE THREAD

**Issue by matiwinnetou** [cardano-foundation/developer-portal#651]
https://github.com/thaddeusdiamond/cardano-nft-vending-machine

**Comment by rdlrt** [comment]
Apologies if I sound pedantic/paranoid - but a bit concerned with the account history (which was ~dormant with 2 commits in past few years, and then creation of this repo with all commits on the same day):
- do we know if the intention of the author is to keep this up to date?
- are there existing users/projects using this library (which would drive contributions to this repository in case author moves on)?

**Comment by katomm** [comment]
Follow up on this: they seem to have updated the repo every now and then also, forks and stars grew over time.

**Comment by rphair** [comment]
@katomm @rdlrt @matiwinnetou it seems like a good addition to me (I'm guessing this is a suggestion for Builder Tools?).  In my experience the author is a reputable person who's contributed to the CIP process in the past, both through his own submissions & peer review of other proposals, and code has been maintained as of about a month ago.

**Comment by rphair** [comment]
Continued in https://github.com/cardano-foundation/developer-portal/pull/1094.
