### ISSUE TITLE
Minting NFT with user guide

### ISSUE THREAD

**Issue by nftizate** [cardano-foundation/developer-portal#660]
Hello,

I' have followed your guide: [developers.cardano.org/docs/native-tokens/minting-nfts/](https://developers.cardano.org/docs/native-tokens/minting-nfts/)

All runs smoothly but when I explore the metadata of the minted NFT, the "721" field is missing.

I have also opened a [github bug](https://github.com/input-output-hk/cardano-node/issues/3994) in [input-output-hk](https://github.com/input-output-hk/cardano-node/issues/3994) in cardano-cli 1.33.0 - linux-x86_64 - ghc-8.10 [git rev](https://github.com/input-output-hk/cardano-node/commit/b97e5fad59753c49e2725edbdc6e3b30926c266a) 

Any clues?

Regards

Javier

**Comment by rdlrt** [comment]
Did you check the [latest reply](https://github.com/input-output-hk/cardano-node/issues/3994#issuecomment-1148938354)?

**Comment by fill-the-fill** [comment]
Issue solved and closed by @nftizate in [here](https://github.com/input-output-hk/cardano-node/issues/3994#issuecomment-1148938354).
