### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by chrispalaskas** [cardano-foundation/developer-portal#663]
In https://developers.cardano.org/docs/stake-pool-course/handbook/generate-stake-pool-keys the following two are missing:
Generate VRF Key pair
Generate Cold keys

I found them at https://docs.cardano.org/getting-started/use-cli
I wrote a python script that does the whole SPO registration flow:
https://github.com/chrispalaskas/cardano-skepsis-toolbox/blob/2-add-register-spo/registerSPO.py

**Comment by sanskys** [comment]
since Stake Pool revamp is done and it includes both they keys, this issue can be closed?

**Comment by rphair** [comment]
yes @sanskys I believe so.
