### ISSUE TITLE
Stake pool operation in test net

### ISSUE THREAD

**Issue by Howard1972** [cardano-foundation/developer-portal#669]
Hello Cardano support team,

I ran into trouble while registering me as a stake pool operator at Cardano test network. All files listed under https://developers.cardano.org/docs/stake-pool-course/handbook/register-stake-pool-metadata#submit-the-transaction are successful created. In the very last step of submitting the final transaction the following error occurs:

Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [DelegsFailure (DelplFailure (DelegFailure (StakeDelegationImpossibleDELEG (KeyHashObj (KeyHash "c3d0f9eb3f3be717777ba60e2a430dad22ae3a8ed0e7733f9a9781c2")))))])

What exactly does this message tell me about the cause? What was done incorrectly?
Below I've attached the list of commands ran successful till the last one.

export TN="--testnet-magic 1097911063"

cardano-cli address key-gen \
    --verification-key-file payment.vkey \
    --signing-key-file payment.skey

cardano-cli stake-address key-gen \
    --verification-key-file stake.vkey \
    --signing-key-file stake.skey

cardano-cli address build \
    --payment-verification-key-file payment.vkey \
    --stake-verification-key-file stake.vkey \
    --out-file payment.addr \
    $TN

cardano-cli stake-address build \
    --stake-verification-key-file stake.vkey \
    --out-file stake.addr \
    $TN

cardano-cli transaction build \
    --alonzo-era \
    --tx-in faf5b885c37644e6b472b8f9ed82eef11859a6a6afc245a269cd475feb4a4826#0 \
    --tx-out $(cat payment.addr)+1000000 \
    --change-address $(cat payment.addr) $TN  \
    --out-file tx.raw \
    --certificate-file stake.cert \
    --invalid-hereafter 61965700 \
    --witness-override 2

cardano-cli transaction build \
    --alonzo-era \
    --tx-in faf5b885c37644e6b472b8f9ed82eef11859a6a6afc245a269cd475feb4a4826#0 \
    --tx-out $(cat payment.addr)+997825523 \
    --change-address $(cat payment.addr) $TN \
    --out-file tx.raw \
    --certificate-file stake.cert \
    --invalid-hereafter 61965700 \
    --witness-override 2

cardano-cli transaction sign \
    --tx-body-file tx.raw \
    --signing-key-file payment.skey \
    --signing-key-file stake.skey \
    $TN \
    --out-file tx.signed

cardano-cli transaction sign \
    --tx-body-file tx.raw \
    --signing-key-file payment.skey \
    --signing-key-file stake.skey \
    $TN \
    --out-file tx.signed

cardano-cli transaction submit \
	--tx-file tx.signed \
	$TN

#cold counter
cardano-cli node key-gen \
--cold-verification-key-file cold.vkey \
--cold-signing-key-file cold.skey \
--operational-certificate-issue-counter-file cold.counter

#generate vrf kes
cardano-cli node key-gen-VRF \
--verification-key-file vrf.vkey \
--signing-key-file vrf.skey

#kes key
cardano-cli node key-gen-KES \
--verification-key-file kes.vkey \
--signing-key-file kes.skey

cardano-cli node issue-op-cert \
--kes-verification-key-file kes.vkey \
--cold-signing-key-file cold.skey \
--operational-certificate-issue-counter cold.counter \
--kes-period 478 \
--out-file node.cert

cardano-cli stake-pool metadata-hash --pool-metadata-file <(curl -s -L -k https://mbt-rfid.de/stakePool.json)

cardano-cli stake-pool registration-certificate \
    --cold-verification-key-file cold.vkey \
    --vrf-verification-key-file vrf.vkey \
    --pool-pledge 500000000 \
    --pool-cost 340000000 \
    --pool-margin 1 \
    --pool-reward-account-verification-key-file stake.vkey \
    --pool-owner-stake-verification-key-file stake.vkey \
    $TN \
    --pool-relay-ipv4 212.227.212.214 \
    --pool-relay-port 6001 \
    --metadata-url https://mbt-rfid.de/stakePool.json \
    --metadata-hash 0fb8d90714f577372c5fcd1c440dc9addae581df6162c441361f706b7a3d00d9 \
    --out-file stake.cert

cardano-cli stake-address delegation-certificate \
    --stake-verification-key-file stake.vkey \
    --cold-verification-key-file cold.vkey \
    --out-file delegation.cert

cardano-cli transaction build-raw \
    --tx-in 0308a059918b96ebc3422a3faa03294b8c39f56cfe58d7606bb94ff0c8fa4f3a#0 \
    --tx-out $(cat payment.addr)+0 \
    --invalid-hereafter 0 \
    --fee 0 \
    --out-file tx.draft \
    --certificate-file stake.cert \
    --certificate-file delegation.cert

cardano-cli query protocol-parameters $TN --out-file protocol.json

cardano-cli transaction calculate-min-fee \
	--tx-body-file tx.draft \
	--tx-in-count 1 \
	--tx-out-count 1 \
	--witness-count 3 \
	--byron-witness-count 0 \
	$TN \
	--protocol-params-file protocol.json

cardano-cli transaction build-raw \
    --tx-in 0308a059918b96ebc3422a3faa03294b8c39f56cfe58d7606bb94ff0c8fa4f3a#0 \
    --tx-out $(cat payment.addr)+497628562 \
    --invalid-hereafter 61976000 \
    --fee 196961 \
    --out-file tx.raw \
    --certificate-file stake.cert \
    --certificate-file delegation.cert

cardano-cli transaction sign \
    --tx-body-file tx.raw \
    --signing-key-file payment.skey \
    --signing-key-file stake.skey \
    --signing-key-file cold.skey \
    $TN \
    --out-file tx.signed

cardano-cli transaction submit \
    --tx-file tx.signed \
    $TN

Does this issue is created while registration is necessary to wait until a registration period to finish that procedure or is it because of that I did something missing?

I would appreciate any comment. Thank you!

**Comment by sanskys** [comment]
since Stake Pool revamp is done and is specific to Pre-prod test net, this issue can be closed?

**Comment by rphair** [comment]
yes @sanskys I think this has been covered.
