### ISSUE TITLE
Add new tag "DAO tooling" for showcase section

### ISSUE THREAD

**Issue by thenic95** [cardano-foundation/developer-portal#680]
- DAOs are coming to Cardano and so are the tools needed to manage them
- Currently we don't have a dedicated "DAO tooling" tag in the showcase section to display those projects
- Should we add the tag "DAO tooling" to the available tags?

- The new tag would fit perfectly for this [PR](https://github.com/cardano-foundation/developer-portal/pull/674)

**Comment by katomm** [comment]
Having this tag for #674 makes a lot of sense. I'd go with "DAO tool" instead of "DAO tooling". I'd suggest to remove "wallet".

**Comment by katomm** [comment]
I'm closing this, because we did the tag and merged it. (in #677)

**Comment by thenic95** [comment]
The tag hasn't been created yet. I still need to open a PR regarding this. Could we keep this issue open for now?
