### ISSUE TITLE
Docusaurus errors during bootstrap.

### ISSUE THREAD

**Issue by Kais3rP** [cardano-foundation/developer-portal#683]
I tried to fork the project and run it, but docusarus fails to generate the sidebar:
```
ValidationError: themeConfig.hideableSidebar has been moved to themeConfig.docs.sidebar.hideable.
```

This is probably due to Docusaurus update,  hence **docusaurus.config.js** has to be updated accordingly:

```
 //hideableSidebar: true,
    docs: {
      sidebar: { hideable: true },
    },
```

Then it triggers 2 warnings and 3 errors:

```
[WARNING] No docs found in "native-tokens/token-registry": can't auto-generate a sidebar.
[WARNING] No docs found in "governance/cardano-improvement-proposals": can't auto-generate a sidebar.
[ERROR] Sidebars file at "D:\dev\opensource\developer-portal\sidebars.js" failed to be loaded.
[ERROR] Loading of version failed for version current
[ERROR] Error: Sidebar category Token Registry has neither any subitem nor a link. This makes this item not able to link to anything.
```

It looks like there is not any `/token-registry` directory in `/native-tokens/` the same goes for `/cardano-improvement-proposals` . Were they deleted on purpose ?

**Comment by fill-the-fill** [comment]
Did you run `yarn build`?

**Comment by katomm** [comment]
Your assessment is correct on the updated Docusaurus. Your version is newer, therefore you are running into this issue. The needed files will be downloaded after the first ´yarn build´. (which will only succeed if you address the update issue ofc)

**Comment by Kais3rP** [comment]
Oh, I had no idea a manual build was needed in order to execute the static generation, I thought that like NextJS in dev mode it automatically performed a build, it's the first time I use *docusaurus* and now I saw the build scripts that fetch the extra docs. Thanks.

**Comment by katomm** [comment]
Yes, an arbitrary decision. Depending on what you are working on, it makes sense to change it locally for yourself. I think in principle most people should not reload all things with every developer build. (and that was the reason for not doing it.)
