### ISSUE TITLE
Information about Virtual Machines removed from testnets.cardano.org

### ISSUE THREAD

**Issue by thenic95** [cardano-foundation/developer-portal#711]
Hi,

I just noticed that the sites we link from [Virtual-machines-and-programming-languages](https://developers.cardano.org/docs/get-started/testnets-and-devnets/#virtual-machines-and-programming-languages) for KEVM, IELE, and EVM have been removed from testnets.cardano.org.

I couldn't find any new pages, and IO confirmed they had been removed. 

How could we re-write this section?

**Comment by rdlrt** [comment]
IMO - it's not a good idea to document anything that's not yet ready for mainnet integration, as historically - months/years of efforts spent over a specific project/path has been ditched due to feasability/complications/efforts/.. etc.

**Comment by katomm** [comment]
@rdlrt What is your suggestion? Just removing KEVM, IELE and GLOW?

**Comment by rdlrt** [comment]
> @rdlrt What is your suggestion? Just removing KEVM, IELE and GLOW?

Yip

**Comment by katomm** [comment]
@thenic95 can we close this?

**Comment by thenic95** [comment]
Absolutely!
