### ISSUE TITLE
Testnet Faucet returns Server Error

### ISSUE THREAD

**Issue by thenic95** [cardano-foundation/developer-portal#735]
Hi,

thanks to community member DRAGO we discovered that the tAda faucet is not working.

Anyone has any insights on how this could be resolved?
![image](https://user-images.githubusercontent.com/61423239/184131996-74daf163-8f5a-4110-b031-f86ead5c8e69.png)

**Comment by rdlrt** [comment]
The faucet has been iffy at best for a while. Given that the testnet network is anyways on the road to reset, I wouldn't expect a quick action - but can have some funds that I can share with someone interested

**Comment by thenic95** [comment]
Thanks, @rdlrt, I just tried it again, and it worked.
It seems like whatever caused the issue was fixed :)
