### ISSUE TITLE
Showcase Section - Properly display new additions 

### ISSUE THREAD

**Issue by thenic95** [cardano-foundation/developer-portal#740]
Hi,

I was just thinking that it might be cool to more prominently display new additions to the showcase section.

Is there a way we could automate that without using a dedicated tag where we wouldn't have to open a PR to remove it, once a given time has passed.

**Why would we need that?**

Right now, you can't really tell what projects were recently added if you're not checking out the PRs on GitHub.

I believe it would a lot of value and would be just a cool feature.

Cheers,
Nicolas

**Comment by katomm** [comment]
I think this is a great suggestion. If we want to do this and assuming that people add projects at the end of the array (which is usually the case) we would need to look at the last x entries and list them with a dedicated category tag. That's all.

**Comment by katomm** [comment]
nice poll, I mean PR: #749
