### ISSUE TITLE
Create different pull request templates

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#742]
We need to create different pull request templates that are suitable for their purpose, like: 

- add a showcase
- add a builder tool
- documentation

(it should also automatically set the right label)

**Comment by fill-the-fill** [comment]
Suggestion for the new PR template

👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Please complete a Checklist
2. Select **one of 3 templates below* that fits your contribution
3. Remove this text as well as the other templates
4. Fill in all sections of the template
5. Click "Create pull request"

## Checklist



- [ ] I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
- [ ] **If this is a builder tool addition**: I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
- [ ] **If this is a showcase addition**: I have read the[Showcase Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js)
- [ ] I have ran `yarn build` after adding my changes **without getting any errors**. 

## Builder Tool addition



* Title: *Project name*
* Description: *Describe your project* 
* Website:   <link_to_project>
* Getstarted: <link_to_getstarted_page>
* Tags:
  * `chainindex`
  * `cli`
  * `golang`
  * `IDE`
  * `java`
  * `javascript`
  * `marlowe`
  * `net`
  * `nft`
  * `operatortool`
  * `oracle`
  * `plutus`
  * `python`
  * `rust`
  * `purescript`
  * `websocket`
  * `http`
  * `json`
  * `haskell`
  * `typescript`
  * `wallet`
  * `serialization`
  * `sdk`
  * `redis`
  * `sql`
  * `lowlevel`
  * `testing`
  * `hosted`

## Showcase addition



* Title: *Project name*
* Description: *Describe your project*
* Website:   <link_to_project>
* Source: <link_to_source_code>
* Tags:
  * `analytics`
  * `daotool`
  * `dex`
  * `ecosystem`
  * `explorer`
  * `educational`
  * `game`
  * `gateway`
  * `identity`
  * `marketplace`
  * `minting`
  * `opensource`
  * `pooltool`
  * `metadata`
  * `token`
  * `nftproject`
  * `nftsupport`
  * `opensource`
  * `wallet`
  * `catalyst`
  
## Updating documentation or Bugfix

**Comment by fill-the-fill** [comment]
> Suggestion for the new PR template
> 
> 👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.
> 
> 1. Please complete a Checklist
> 2. Select *_one of 3 templates below_ that fits your contribution
> 3. Remove this text as well as the other templates
> 4. Fill in all sections of the template
> 5. Click "Create pull request"
> 
> ## Checklist
> <-- Please fill the boxes with [x] before submitting a pull request -->
> 
> * [ ]  I have read the [How to Contribute](https://developers.cardano.org/docs/portal-contribute/).
> * [ ]  **If this is a builder tool addition**: I have read the [Builder Tool Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js)
> * [ ]  **If this is a showcase addition**: I have read the[Showcase Requirements](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/showcases.js)
> * [ ]  I have ran `yarn build` after adding my changes **without getting any errors**.
> 
> ## Builder Tool addition
> <-- Provide information for every bullet in the list below. The tags you select must match the tags in your changes to the builder-tools.js -->
> 
> * Title: _Project name_
> * Description: _Describe your project_
> * Website:   <link_to_project>
> * Getstarted: <link_to_getstarted_page>
> * Tags:
>   
>   * `chainindex`
>   * `cli`
>   * `golang`
>   * `IDE`
>   * `java`
>   * `javascript`
>   * `marlowe`
>   * `net`
>   * `nft`
>   * `operatortool`
>   * `oracle`
>   * `plutus`
>   * `python`
>   * `rust`
>   * `purescript`
>   * `websocket`
>   * `http`
>   * `json`
>   * `haskell`
>   * `typescript`
>   * `wallet`
>   * `serialization`
>   * `sdk`
>   * `redis`
>   * `sql`
>   * `lowlevel`
>   * `testing`
>   * `hosted`
> 
> ## Showcase addition
> <-- Provide information for every bullet in the list below. The tags you select must match the tags in your changes to the showcase.js -->
> 
> * Title: _Project name_
> * Description: _Describe your project_
> * Website:   <link_to_project>
> * Source: <link_to_source_code>
> * Tags:
>   
>   * `analytics`
>   * `daotool`
>   * `dex`
>   * `ecosystem`
>   * `explorer`
>   * `educational`
>   * `game`
>   * `gateway`
>   * `identity`
>   * `marketplace`
>   * `minting`
>   * `opensource`
>   * `pooltool`
>   * `metadata`
>   * `token`
>   * `nftproject`
>   * `nftsupport`
>   * `opensource`
>   * `wallet`
>   * `catalyst`
> 
> ## Updating documentation or Bugfix
> <-- Help us understand your motivation by explaining why you decided to make this change. We must be able to understand the purpose of your change from this description. Does this fix a bug? Does it close an issue? If some please mention it. -->

@rphair @rdlrt @katomm @os11k @thenic95 @lodl What do you guys think?

**Comment by katomm** [comment]
@fill-the-fill Technically looks good but the issue was about (real) different PR templates, that people can select :) Not all in one and people need to cut out manually things. This is the only way to achieve the automated labelling solution (that I'm aware of)

**Comment by fill-the-fill** [comment]
> @fill-the-fill Technically looks good but the issue was about (real) different PR templates, that people can select :) Not all in one and people need to cut out manually things. This is the only way to achieve the automated labelling solution (that I'm aware of)

I see, I will look into separating them into multiple templates.

**Comment by os11k** [comment]
I don't now, honestly. I prefer as it is now, new change seems ok, but I think this change will add more time needed to create PRs. I personally think making this process more time consuming is not really what I would prefer, but again it is me. Some big projects has very difficult and huge PR templates and it works for them. I personally prefer when it is super straightforward, but again I'm quite new reviewer in this project and I don't touch good portions of PRs(which I don't have understand or I'm not confident), so take my opinion with a grain of salt.

**Comment by fill-the-fill** [comment]
> I don't now, honestly. I prefer as it is now, new change seems ok, but I think this change will add more time needed to create PRs. I personally think making this process more time consuming is not really what I would prefer, but again it is me. Some big projects has very difficult and huge PR templates and it works for them. I personally prefer when it is super straightforward, but again I'm quite new reviewer in this project and I don't touch good portions of PRs(which I don't understand or in where I'm not confident), so take my opinion with a grain of salt.

The only major modification I've made is adding checkboxes. The reason behind that is that most of new users constantly don't follow the guidelines and make multiple mistakes in PR including not testing the code locally.

**Comment by rphair** [comment]
In my experience if there's an inappropriate section in a PR or issue template (e.g. Builder Tools & all its tags, if I've got a Showcase item) then I'll just delete it without too much trouble.

I do like @katomm's suggestion & would like to see @fill-the-fill's response about separating into multiple templates... but I don't know how that workflow would go on GitHub, so I can't vote for that idea... but I would like to see it in action before deciding, especially to see if it's clear enough to the naive user how to select from multiple templates. 🧐

**Comment by rphair** [comment]
(**n00b question alert**) I am also realising that use of the `getstarted:` tag is confusing even to me, even after having seen many case studies in the last couple of months.  Specifically:

- I've seen us refer people to the documentation in the live Dev Portal about how this tag is used (most recently https://github.com/cardano-foundation/developer-portal/pull/784#discussion_r974920103)... and I've searched for this several times and still can't find it.
- The comments in `/src/data/builder-tools.js` describe a couple of error conditions but not the pattern of correct usage.
- I recall (maybe wrongly) that we've told contributors `getstarted:` has to be a local Markdown page, but I can see several pages where the pages aren't local, and that all but one are links to HTML:
```
$ grep getstarted: src/data/builder-tools.js | grep -i http
    getstarted: "https://input-output-hk.github.io/cardano-wallet/",
    getstarted: "https://github.com/input-output-hk/cardano-graphql#getting-started",
    getstarted: "https://www.rosetta-api.org/docs/getting_started.html",
    getstarted: "https://github.com/input-output-hk/cardano-addresses#command-line",
    getstarted: "https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc/getting-started.md",
```

So please at least for my benefit tell me _where the definitive guide is for usage of `getstarted:`_ so I know how to advise contribors properly:
If there is such a link, is it in the navigation of the Dev Portal where everybody can see it?
Especially if not in that navigation, I think that link should be included in the resulting Builder Tool template so contributors can check the usage properly for themselves 🤓

**Comment by katomm** [comment]
Yes, @rphair the confusion here is partly my fault since the concept was not described anywhere before. (At least how it was thought initially) I always wanted to add it to the https://developers.cardano.org/docs/portal-contribute/ 

So the initial idea of the "getstarted"tag/link was indeed to have people write a subsite on the developer portal, to whet people's appetite for the tool AND also to be found much better via search. I think this advantage is underestimated, if a tool has a getstarted page in the portal, developers are more likely to find the solutions via search. (please keep this in mind when reading further)

Questions now: 
Should we enforce local "get started"-pages? No, of course not. 
Should we allow external "get started"-pages? Probably. 
Wouldn't that make it redundant at all? Probably. 
Should we explain this better? Yes

Since we got rid of the "get started"-tags through the PR from @KtorZ who reworked all the labels we can discuss or re-discuss the pros and cons of the "get started"-function in principle.

**Comment by rphair** [comment]
> @katomm: we can discuss or re-discuss the pros and cons of the "get started"-function in principle.

I hope I have understood the question correctly... from both my end-user and my developer perspectives, the most important thing for me is to have a top level [HOWTO](https://en.wikipedia.org/wiki/Linux_Documentation_Project#Content) page which is practically oriented: neither a marketing oriented web site home or landing page nor a detail oriented reference manual... somewhere in between.

Because it cannot matter to most users and devs where this page is actually located (and most of our open source & crypto documentation will link between web sites & GitHub / wiki pages all the time), then it shouldn't matter to us either.  

It's most important for Builder Tool providers to have an environment where they feel comfortable creating this HOWTO material for Dev Portal users (among _all_ users)... but generally that environment won't be the Dev Portal web site and won't generally be in Markdown either.

Mainly I wanted to know what was different about the 5 Builder Tools I listed [here](https://github.com/cardano-foundation/developer-portal/issues/742#issuecomment-1252328743), all with external "get started pages" ... by their age it seems they've also been "grandfathered in" by entering the Dev Portal before the "internal only" rule was enforced (as I've noticed it's been strictly enforced in the two recent examples above).

A good example is the [Rosetta dev portal getstarted page](https://www.rosetta-api.org/docs/getting_started.html) which is external, in HTML, and of perfect utility to our own users... why on earth would we limit new entrants by forcing them to document their tools on a framework they'll generally be less comfortable with, which might not even match their own documentation standards?

So since we've been telling people the Get Started pages _must_ be local, it seems the simplest solution would be to _stop_ telling people that.  Meanwhile we should develop other incentives for people to add additional documentation pages to the Dev Portal itself... and mentioning SEO & exposure very emphatically to new audiences (though the Portal "Contribute" pages and/or PR template) would be a good place to start 🤠

**Comment by fill-the-fill** [comment]
Going back to the initial discussion, I've managed to find a way to split template into multiple templates, would like to hear your opinion on that.

If everyone is okay with it, I can use the template I've posted in the discussion above and split it.

https://user-images.githubusercontent.com/60065019/197272148-703b015f-3680-44d9-826d-2e9d022434c5.mov

**Comment by rphair** [comment]
neat trick 🤓 ... sure I'm OK with it ✅

**Comment by fill-the-fill** [comment]
#845 has been merged into staging
