### ISSUE TITLE
Testnet faucet - recaptcha invalid domain for site key

### ISSUE THREAD

**Issue by BharatAtEMURGOIO** [cardano-foundation/developer-portal#748]
@katomm 
The preview/preprod update for the testnet faucet at link (https://testnets.cardano.org/cardano-testnet/tools/faucet)   seems to be unusable due to a reCaptcha error "ERROR for site owner:
Invalid domain for site key". The funds transfer will not proceed until this is fixed.

FIX: Maybe refer the steps here https://help.whmcs.com/m/troubleshooting/l/1189046-troubleshooting-recaptcha-invalid-domain-for-site-key

This needs to be fixed so that we can start using the faucet for preview/preprod networks.

Thanks in advance!

**Comment by rdlrt** [comment]
Might need to transfer it to
https://github.com/input-output-hk/cardano-documentation

**Comment by BharatAtEMURGOIO** [comment]
oh. I'm sorry. I didn't realize that this was maintained by IOHK. Sure, will close it here, and I will check if this issue still exists and report it in the IOHK cardano-documentation issue tracker.
