### ISSUE TITLE
404 error page on cardano-keys page

### ISSUE THREAD

**Issue by futuristudios** [cardano-foundation/developer-portal#751]
there's a broken link at [https://docs.cardano.org/core-concepts/cardano-keys/](https://docs.cardano.org/core-concepts/cardano-keys/)

it's not under the developer portal but under docs - but there's not docs repo afaik.

**Comment by rphair** [comment]
The issue queue for that repo is here: https://github.com/input-output-hk/cardano-documentation/issues

This can be found by clicking the GitHub logo (where it also says "Star") in the upper right corner of the link you posted... this works even for 404 pages 🤓
