### ISSUE TITLE
Deprecated Cardano Testnets

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#759]
We need to update all references Cardano Testnet.  

Also please note faucet, for example, will only work when being accessed from:
https://docs.cardano.org/cardano-testnet/tools/faucet
instead of:
https://testnets.cardano.org/cardano-testnet/tools/faucet

It's worth updating any older links to be set directly from the docs site.
Here's the starting overview page, and any other details can be found in the navigation:
https://docs.cardano.org/cardano-testnet/overview

New environments should be on https://book.world.dev.cardano.org/environments.html afaik

There are also new Daedalus test versions uploaded here: https://docs.cardano.org/cardano-testnet/daedalus-testnet

**Comment by cherrries** [comment]
<img width="1020" alt="Screen Shot 2022-09-14 at 3 07 00 PM" src="https://user-images.githubusercontent.com/101910862/190241350-ad461a42-8d02-4e94-8c7d-e487fc5f1afd.png">


These links are broken

**Comment by pgrange** [comment]
Especially true for this page: https://developers.cardano.org/docs/get-started/running-cardano#testnet--sandbox

I was so proud I had sync a full testnet node and then realized that all the cool kids were using the preview network 😿

**Comment by katomm** [comment]
This is getting addressed in #963, therefore I'm closing this.
