### ISSUE TITLE
Add StakePoolOperator Scripts by Martin

### ISSUE THREAD

**Issue by katomm** [cardano-foundation/developer-portal#778]
its the wrong thread here, but maybe someone can help me to bring the "StakePoolOperator Scripts" to the developer portal? i am so busy and never had the time to dig into the dev portal usage... but they should be on the portal, many are using them on a daily base.

url: https://github.com/gitmachtl/scripts
readme: https://github.com/gitmachtl/scripts/blob/master/cardano/mainnet/README.md

_Originally posted by @gitmachtl in https://github.com/cardano-foundation/developer-portal/issues/777#issuecomment-1250024761_

**Comment by rphair** [comment]
Completed with merge of https://github.com/cardano-foundation/developer-portal/pull/779.

**Comment by gitmachtl** [comment]
Thank you very much! ❤️
