### ISSUE TITLE
Cardano Operations Book: discussion, how to link there

### ISSUE THREAD

**Issue by rphair** [cardano-foundation/developer-portal#797]
Someone just [referenced this site](https://github.com/cardano-foundation/CIPs/pull/332#issue-1383864192) from the CIP repository today: https://book.world.dev.cardano.org

Also titled the _Cardano World Repository_, it's still pretty empty but appears to be coming from an official source and has some information that's hard to find documented anywhere else (e.g. the new networks evolved from the Testnet that I've only seen documented informally so far).

The currently mostly greyed-out page outline has some overlap with the material here in the Dev Portal (`cardano-wallet`, Ogmios).  More generally I was wondering if anyone knows about its development plan & timeline, and can post ideas about it here, in the hope when ready that this will be properly introduced on & linked from the Dev Portal.

**Comment by rphair** [comment]
p.s. I've also now noticed this site was referenced earlier by @katomm in https://github.com/cardano-foundation/developer-portal/issues/759#issue-1363275769 - regarding the same material (documentation of Cardano environments)

**Comment by rdlrt** [comment]
> The currently mostly greyed-out page outline has some overlap with the material here in the Dev Portal (cardano-wallet, Ogmios).

I think the original intention of that site was to include a lot more information, but IMO - the current state (except index) is good, it shouldn't onboard more as it will likely have yet another overlap with instructions on : dev portal (community maintained), docs.cardano.org (IO maintained), github repo of components (readme.md+docs folder) and other community sites (eg: coincashew) for step-by-step instructions. The more the websites referenced, greater are chances of confusion/chaos/outdated (or different styles of information).

Instead, we could use the config/topology file/genesis/etc references as-is for downloads, but need to also be mindful of standards:
For instance, P2P - while works - is still not production-ready (the n2n versions are still changing), might not be best idea to include default templates with P2P turned on. But given that it's only enabled on non-mainnet networks, except preprod (supposed to replicate mainnet) - other networks having that config might be OK.

Additionally, preprod/preview networks are both supposed to be reset soon, and we should be having a new community initiated testnet as well.

With the above changes upcoming, I would prefer if we could defer changes for now - until there is clearer picture in coming weeks

**Comment by rphair** [comment]
thanks @rdlrt that's much as I thought... the strategy of "one web site to rule them all" often ends up not achieving that goal on an organically growing project.  I've only posted this issue to give contributors a place to track how this site is developing, so we might link there if & when it reaches some kind of maturity. 😎

**Comment by katomm** [comment]
I also think the "juicy stuff" is on https://book.world.dev.cardano.org/environments.html we can just link that.

**Comment by rphair** [comment]
> we can just link that.

This link was in fact added by https://github.com/cardano-foundation/developer-portal/pull/814 but the link isn't well presented for either UX or SEO, so I've opened up https://github.com/cardano-foundation/developer-portal/pull/846.

Once that's merged I think this can be closed because the consensus seems to be that the only thing useful about this site is its Environments page.
