### ISSUE TITLE
Faucet Embed is clipping

### ISSUE THREAD

**Issue by blubotsNFT** [cardano-foundation/developer-portal#812]
When in the Testnet faucet section of the integrate cardano documentation [the Faucet ](https://developers.cardano.org/docs/integrate-cardano/testnet-faucet/)section is clipping the tADA submission process, so much so that the captcha and the address input sections are not selectable.
![faucet_issue](https://user-images.githubusercontent.com/103647590/194040850-21da70f3-592a-4a32-8533-5db0357a7eff.png)

**Comment by rphair** [comment]
I just set up a local testing branch for this, but found that the embedding doesn't work in a local branch (or more likely on a domain that doesn't match the canonical domain).  Any suggestions how to test & debug this one?  If I had some idea how this works I might go at it by setting the container properties plus maybe adding a narrow-screen media query if allowed.

**Comment by katomm** [comment]
Please also see #759

**Comment by blubotsNFT** [comment]
@rphair unfortunately I'm not sure how to test or debug it, I only spotted the bug while going through the documentation. Hopefully someone here smarter than myself might be able to give us an answer! :)
