### ISSUE TITLE
Missing CIP36

### ISSUE THREAD

**Issue by gitmachtl** [cardano-foundation/developer-portal#835]
CIP36 - the new standard for voting/governance/catalyst registration/delegation/deregistration - is missing in the [CIP collection](https://developers.cardano.org/docs/governance/) on the dev portal

**Comment by fill-the-fill** [comment]
@gitmachtl On it, found the problem, actually we are missing more than CIP36, will be opening a PR very soon

**Comment by fill-the-fill** [comment]
#848 has been merged into staging
