### ISSUE TITLE
Add cabal update and node reinstall procedure

### ISSUE THREAD

**Issue by dgarey** [cardano-foundation/developer-portal#864]
Before we build the node and cli we need to run _cabal update_

**Comment by rphair** [comment]
The problem in the originally reported title isn't always true: it's definitely not needed on a fresh install of GHC for the first build of the node.  But I agree something should be added so people don't have to figure it out for themselves when `cabal update` is needed and why.

A lot of outdated & half-written documentation is going to expire when we finish rewriting the tools appropriate to stake pool operators.  Some material _does_ have the `cabal update` - including this one, which seems to have disappeared from the menus: https://developers.cardano.org/docs/stake-pool-course/handbook/install-cardano-node-written/

I think the proper way to fix this is to include a subsection for **Upgrade the node** (or maybe a separate page) in the installation procedure: for both the original `cardano-node` installation instructions and the SPO specific instructions (assuming they are to remain separate)

For SPO documentation, adding `cabal update` and/or addressing the "node upgrade" topic may already be in the works, but I don't see it in the latest draft (https://github.com/cardano-foundation/developer-portal/blob/revamp-stake-pool-course/docs/stake-pool-guide/node-installation-process.md).  @sanskys is it part of your plan to include this?

In any case there's a specific topic in our rewrite plan https://github.com/cardano-foundation/developer-portal/issues/737 for **Cardano Node Upgrades** where it should be addressed.  I've called attention to this matter in the latest comment.

BTW generally issues like this should be _far_ more specific: in this case, the pages and sections you're referring to, and if possible the language & procedure you think should be there.

**Comment by sanskys** [comment]
we should take up this topic in the chapter Stake Pool Maintainance -> Cardano Node Upgrades #737

**Comment by os11k** [comment]
What you think if we will add just:

"For some installations you might encounter the following warning: Warning: The package list for 'cardano-haskell-packages' does not exist. Run 'cabal update' to download it.. The warning is self-explanatory and you will need to run cabal update before moving on."

I added such note for Mac installation, I think we can put same for Linux. What you think @rphair ?

**Comment by dgarey** [comment]
@rphair I agree that a message like this would go far.

**Comment by rphair** [comment]
@dgarey @os11k - yes, I think adding that line is a good idea.  But it's not the only condition we might want to run `cabal update`, is it?  I actually run it every time I rebuild the node.. in fact (superstitiously? OCD?) I run it 3 times... first time downloads the dependencies, second time confirms the dependencies are there, and the third time shows there's nothing left to do before the compile.

So maybe someone with better general knowledge of GHC should explain exactly when and how this command is to be used.  Then @sanskys I think those suggestions can be noted to add to the pending material in #737.

**Comment by os11k** [comment]
My main objective here is to cover cardano-node build from scratch, I'm not so concerned about rebuilding and etc. I personally think that such note should be there if we provide build manual and seems for building that is mandatory step now. So I think we should include such note under cardano-node build for Linux too

**Comment by rphair** [comment]
@os11k good enough for me 🤓

**Comment by os11k** [comment]
I will prepare PR this week. Thank you @rphair & @dgarey 

Unfortunately I do not build cardano node from scratch usually and that why I overlooked this issue.

**Comment by rphair** [comment]
I've done it every time except the last one (`1.35.5` which I got from the binary package)... I keep my own command notes scripted so I'll double check it @os11k against what you prepare.

**Comment by sanskys** [comment]
> @dgarey @os11k - yes, I think adding that line is a good idea. But it's not the only condition we might want to run `cabal update`, is it? I run it every time I rebuild the node.. in fact (superstitiously? OCD?) I run it 3 times, because the response is slightly different each of those times... first time downloads the dependencies, second time confirms the dependencies are there, and the third time shows there's nothing left to do before the compile.
> 
> So maybe someone with better general knowledge of GHC should explain exactly when and how this command is to be used. Then @sanskys I think those suggestions can be noted to add to the pending material in #737.

We could also add a new Chapter for node upgrades?

**Comment by rphair** [comment]
@sanskys it's already in there for at least the last few versions of the working outline (https://github.com/cardano-foundation/developer-portal/issues/737#issuecomment-1217978885)

### Stake Pool Maintenance    
- [x] Rotate KES
- [x] Update Registration
- [ ] **Cardano Node Upgrades**
