### ISSUE TITLE
LLVM version 13 needed to build on Mac M1 systems

### ISSUE THREAD

**Issue by rezabaram** [cardano-foundation/developer-portal#881]
Following https://github.com/cardano-foundation/developer-portal/blob/staging/docs/get-started/installing-cardano-node.md 
I ran into issues while building cardano-node from the source on Mac M1. I had to downgrade and link to llvm13 to make it work. "brew install llvm" installs llvm15 by default. It would be nice it that could be mentioned in the instructions.

With llvm15 I would get errors like:

Building library for base-compat-0.12.2..
[  1 of 122] Compiling Control.Concurrent.Compat ( src/Control/Concurrent/Compat.hs, dist/build/Control/Concurrent/Compat.o, dist/build/Control/Concurrent/Compat.dyn_o )
Cannot specify -O# and --passes=/--foo-pass, use -passes='default<O#>,other-pass'
`opt' failed in phase `LLVM Optimiser'. (Exit code: 1)

**Comment by rphair** [comment]
@rezabaram if you can recommend some text to that section (https://github.com/cardano-foundation/developer-portal/blob/staging/docs/get-started/installing-cardano-node.md#you-will-need-to-install-llvm-in-case-you-are-using-m1), to help affected operators work around the problem, you'd be welcome to submit it as a pull request.

If that is impractical for you, please post the revised text / markdown here and I would be happy to create the pull request for you. 🤓

**Comment by os11k** [comment]
Should be fixed by #957
