### ISSUE TITLE
Create nft metadata file withoud ipfs hash to photo. Instead using own https link to photo

### ISSUE THREAD

**Issue by Pashamks** [cardano-foundation/developer-portal#903]
Hello!
I have one question!
Is it possible to create nft metadata file without ipfs link in cardano cli ?
Instead I use https://... link to my photo on my server.
But i receive next error:
Text string metadata value must consist of at most 64 UTF8 bytes, but it consists of 68 bytes.
Full error with metadata file example:
Value out of range within the metadata item 721: {"45993819b9e8798403e91af6ff2e213db7931c9bfb5793ca1dc59f2a":{"TW9uc3RlcjU=":{"description":"monster desc","id":"0","image":"https://<mydomain>/nft-uploads/3/-8585294373491532797.png","name":"Monster5","price":100}}}

**Comment by rphair** [comment]
@Pashamks this issue queue is for content on https://developers.cardano.org - not for technical questions.  Please try asking at:

- https://forum.cardano.org/c/developers/cardano-tokens/150
- https://discord.gg/inputoutput

**Comment by Pashamks** [comment]
The solution to my problem was:
As it says: Strings in CBOR (which the JSON is transformed to for putting it on the chain) are restricted to 64 bytes.
You can give an array of strings instead:
"image": [
    "https://example.com/",
    "nft-uploads/3/-8585294373491532797.png"
],
