### ISSUE TITLE
Issue number -2

### ISSUE THREAD

**Issue by Mirsahibul07** [cardano-foundation/developer-portal#939]
Please advise about my assets at your earliest..!

**Comment by rphair** [comment]
@Mirsahibul07 please check to make sure you have filed this request in the correct place: if so, you need to provide a lot more information.  This issue queue is for requests or queries about the content on the web site [developers.cardano.org](https://developers.cardano.org/).

**Comment by rdlrt** [comment]
[Looks spam](https://github.com/Blockchair/Blockchair.Support/issues/1056) - randomly going to repos and demanding irrelevant info

**Comment by rphair** [comment]
thanks @rdlrt - I didn't think of looking up activity for the username 😖
