### ISSUE TITLE
Broken hydra.iohk.io specifications links

### ISSUE THREAD

**Issue by SmaugPool** [cardano-foundation/developer-portal#988]
Some links to hydra.iohk.io that is not used anymore are not working, for example "Design Specification for Delegation and Incentives in Cardano":

https://hydra.iohk.io/build/790053/download/1/delegation_design_spec.pdf

It is referenced for example on this page:

https://developers.cardano.org/docs/governance/cardano-improvement-proposals/cip-0074/

I would have made a pull request if I knew where those docs are now, but I have no idea.

**Comment by fill-the-fill** [comment]
CIP content is fetched from [CIP Repo](https://github.com/cardano-foundation/CIPs) when running `build`.

So I assume we should mention in CIP Repo regarding link change

**Comment by rphair** [comment]
Thanks @SmaugPool - this is an upstream problem which I've submitted as https://github.com/cardano-foundation/CIPs/issues/485.
